### PR TITLE
Document TrueNAS specific SMB1 support option

### PR DESCRIPTION
**Pull request by Mrt134**
Add entry in services.rst for the new checkbox
Replace the related TrueNAS image.
Add reference point to SMB1 warning in sharing.rst.
TrueNAS HTML build test: no issues.

### CODE REVIEW

**Comment by dlavigne** [comment]
Please hold off on merging as there will be a U6.2 before U7 which does not have this checkbox.

**Comment by dlavigne** [comment]
Also, why 11.1-stable? That's the mucked up branch.

**Comment by Mrt134** [comment]
Sorry, I wasn't aware this branch was messed up. The PR in 54954 was merged to FreeNAS/TrueNAS 11.1 only, so I thought this was the right branch to adjust the 11.1 guide. I can point the PR to a different branch pretty easily though.

**Comment by Mrt134** [comment]
Closing this PR in favor of https://github.com/freenas/freenas-docs/pull/490, which is pointed toward the correct branch.

**Pull request closed without merging**
