### PR TITLE
NAS-100155 Add section and docs for new task manager in GUI.

### PR DESCRIPTION
**Pull request by a-stjohn**
(cherry picked from commit 4f39c032e065e2128166114f91a95d2c04bef3e2)

### CODE REVIEW

**Comment by dlavigne** [comment]
Is this the correct branch for an 11.3-BETA1 ticket?

**Comment by a-stjohn** [comment]
> Is this the correct branch for an 11.3-BETA1 ticket?

@dlavigne I thought this feature was for both 11.2 and 11.3-BETA1. If it's ONLY for 11.3-BETA1, then the correct branch is `angulargui`.

**Comment by dlavigne** [comment]
According to the ticket, it is for BETA1.

**Comment by wblock** [comment]
Not needed, change is only in 11.3-BETA1.

**Pull request closed without merging**
